# Project root relative to this config file
projectRoot: ../../

# Log settings
log:
  debug: false # Enable debug logs
  quiet: false # Disable logs completely

# Tasks to run in given order
tasks:
  - clean:
      directories:
        - ./.theme/.temp
        - ./.theme/content
  - extractDiagrams:
      source: ./
      target: ./.theme/.temp
  - copy:
      extension: .md
      source: ./.theme/.temp
      target: ./.theme/content
  - move:
      extension: .png
      source: ./.theme/.temp
      target: ./.theme/public
  - rename:
      source: ./.theme/content
      find: README.md
      replace: index.md
  - replaceContent:
      extension: .md
      source: ./.theme/content
      oldText: README.md
      newText: index.md
  - fixLinks:
      source: ./.theme/content
      indexFile: index.md
