# Project root relative to this config file
projectRoot: ../../

# Log settings
log:
  debug: false # Enable debug logs
  quiet: false # Disable logs completely

# Tasks to run in given order
tasks:
  - clean:
      directories:
        - ./.theme/.public
        - ./.theme/.temp
        - ./.theme/content
  - touch:
      path: ./.theme/.env.local

  # process and move markdowns to content
  - extractDiagrams:
      source: ./
      target: ./.theme/.temp
      config:
        backgroundColor: '#061819'
        theme: base
        deviceScaleFactor: 1
        themeVariables:
          fontFamily: '"Roboto Mono", monospace'
          fontSize: '14px'
          primaryColor: '#fa465b'
          primaryTextColor: '#f6f6f6'
          primaryBorderColor': '#7c0000'
          lineColor: '#888888'
          secondaryColor: '#092122'
          secondaryTextColor: '#cacaca'
          tertiaryColor: '#163738'
          activationBkgColor: '#fa465b'
  - rename:
      source: ./.theme/.temp
      find: README.md
      replace: index.md
  - replaceContent:
      extension: .md
      source: ./.theme/.temp
      oldText: README.md
      newText: index.md
  - move:
      extension: .md
      source: ./.theme/.temp
      target: ./.theme/content

  # copy all assets to .public
  - copy:
      source: ./.theme/public
      target: ./.theme/.public
  - copy:
      extension: .png
      source: ./
      target: ./.theme/.public
  - move:
      extension: .png
      source: ./.theme/.temp
      target: ./.theme/.public
